version: "3.9"
services:
  ws1:
    container_name: websocket1
    build:
      context: ws
      dockerfile: Dockerfile
    ports:
      - "3000:8080"
    volumes:
      - ./ws:/usr/src/websocket
  ws2:
    container_name: websocket2
    build:
      context: ws
      dockerfile: Dockerfile
    ports:
      - "3001:8080"
    volumes:
      - ./ws:/usr/src/websocket
  redis:
    image: "redis:alpine"
    ports:
      - "6379:6379"
  nginx:
    container_name: loadbalancer
    build:
      context: loadbalancer
      dockerfile: Dockerfile
    ports:
      - "8080:80"